server:
  port: 9900

spring:
  profiles:
    active: dev
  jpa:
    open-in-view: false

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    # driver-class-name: org.postgresql.Driver
    # url: jdbc:postgresql://localhost:5432/sales # jdbc:h2:mem:sales
    url: jdbc:h2:mem:sales
    username: test
    password:
  jpa:
    # database: postgresql
    # database-platform: org.hibernate.dialect.PostgreSQLDialect
    # hibernate:
    #   ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console