spring:
  datasource:
    # driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sales # jdbc:h2:mem:testdb
    username:
    password:
  jpa:
    # database: postgresql
    # database-platform: org.hibernate.dialect.PostgreSQLDialect
    # hibernate:
    #   ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 9900